class Config:
    BASE_URL = "https://automationplayground.com/crm/login.html"
    EMAIL_ADDRESS = "confixhub@yopmail.com"
    PASSWORD = "Qwerasd12@"
    EMAIL = "bello@gmail.com"
    FIRST_NAME = "compete"
    LAST_NAME =  "bell"
    CITY = "New York"
    STATE = "Maryland"
    GENDER = "male"